# Generated by Django 2.0.5 on 2018-07-16 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiman',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
