# Generated by Django 2.0.5 on 2018-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Valuation', '0002_auto_20180716_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qiman',
            name='PE_PB',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qiman',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qiman',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='qiman',
            name='percentile',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='qiman',
            name='roe',
            field=models.FloatField(),
        ),
    ]
